version: '3'

services:
  traefik:
    image: traefik:1.7
    restart: always
#    labels:
#      - "traefik.frontend.rule=Host:api-compte.kickchain.eu"
#      - "traefik.port=8080"
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    container_name: traefik

networks:
  web:
    external: true

