[global]
  sendAnonymousUsage = false
  checkNewVersion = true

[log]
  level = "DEBUG"

[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "web-secure"
      scheme = "https"

  [entryPoints.web-secure]
    address = ":443"

[api]
  dashboard = true
  insecure = true
#  debug = true

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedByDefault = false
  network = "web"

[certificatesRevolvers.letsencrypt.acme]
  email = "louis.barbaglia@epitech.eu"
  storage = "acme.json"
  caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
  [certificatesResolvers.letsencrypt.acme.httpChallenge]
    entryPoint = "web"
