debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.dashboard]
  address = ":8080"
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[api]
entrypoint = "dashboard"
dashboard = true

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "kickchain.eu"
watch = true
exposedByDefault = false

[acme]
email = "louis.barbaglia@epitech.eu"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"

